# Generated by Django 4.0.1 on 2022-02-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Wyślij wiadomość do')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iam', models.CharField(max_length=100, verbose_name='Kontakt Jako')),
                ('fname', models.CharField(max_length=100, verbose_name='Imię')),
                ('lname', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=100, verbose_name='Mail')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon')),
                ('msg', models.TextField(verbose_name='Wiadomość')),
            ],
        ),
    ]
