# Generated by Django 4.0.1 on 2022-01-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Szczegóły',
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Forma Zatrudnienia',
                'verbose_name_plural': 'Formay Zatrudnienia',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Miejsce Pracy')),
            ],
            options={
                'verbose_name': 'Lokalizacja',
                'verbose_name_plural': 'Lokalizacje',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa Stanowiska')),
            ],
            options={
                'verbose_name': 'Stanowisko',
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_created=True, editable=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('posted', models.BooleanField(default=False)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artykuł',
                'verbose_name_plural': 'Arykuły',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_created=True, editable=False)),
                ('posted', models.BooleanField(default=False)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lide_api.details')),
                ('employment_type', models.ManyToManyField(to='lide_api.EmploymentType')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lide_api.locations')),
                ('positon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='lide_api.positions')),
            ],
            options={
                'verbose_name': 'Oferta Pracy',
                'verbose_name_plural': 'Oferty Pracy',
            },
        ),
    ]
