# Generated by Django 4.0.1 on 2022-01-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lide_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News-y'},
        ),
        migrations.AlterField(
            model_name='offers',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Szczegóły'),
        ),
        migrations.RemoveField(
            model_name='offers',
            name='location',
        ),
        migrations.AddField(
            model_name='offers',
            name='location',
            field=models.ManyToManyField(to='lide_api.Locations'),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
