# Generated by Django 4.0.1 on 2022-01-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lide_api', '0002_alter_posts_options_alter_offers_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='post_date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
