# Generated by Django 4.0.1 on 2022-01-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lide_api', '0003_alter_offers_post_date_alter_posts_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='positon',
            new_name='position',
        ),
    ]
