# Generated by Django 3.2.10 on 2022-01-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lide_api', '0004_rename_positon_offers_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='location',
            field=models.ManyToManyField(to='lide_api.Locations', verbose_name='Lokalizacja'),
        ),
    ]
