# Generated by Django 3.2.10 on 2022-01-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lide_api', '0005_alter_offers_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='location',
            field=models.ManyToManyField(to='lide_api.Locations'),
        ),
    ]
