# Generated by Django 3.2.10 on 2022-01-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lide_api', '0006_alter_offers_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lide_api.positions'),
        ),
    ]
