# Generated by Django 4.0.1 on 2022-01-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lide_api', '0007_alter_offers_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='post_date',
        ),
        migrations.AlterField(
            model_name='offers',
            name='edited',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
